const FETCHING_CATEGORIES = 'FETCHING_CATEGORIES';
const FETCHING_MEALS = 'FETCHING_MEALS';
const FETCHING_DISHES = 'FETCHING_DISHES';

const FETCH_LOADING = 'FETCH_LOADING';
const FETCHING_ERROR = 'FETCHING_ERROR';

export {
  FETCHING_CATEGORIES,
  FETCHING_MEALS,
  FETCH_LOADING,
  FETCHING_ERROR,
};
